### PR TITLE
Improved Docs

### PR DESCRIPTION
**Pull request by tannu-priya07**
SearchingThing.Solid

### CODE REVIEW

**Comment by tannu-priya07** [comment]
Improved.docs

**Comment by devel0** [comment]
thx for your review, but SearchAThing is really written that way,
I used it also as namespace ( [example](https://github.com/SearchAThing-old1/SearchAThing.Solid/blob/4731d5fd90d2ba7ce5f14e8b8ac0633024983064/src/SearchAThing.Solid/Face.cs#L44) ) so there is no need to change.

**Comment by tannu-priya07** [comment]
just don't close this pull request.
You may just leave the request as usual for 1 and half month.
thank u

**Comment by devel0** [comment]
sorry, reopened for further reviews, you wellcome.
I closed when PR seems solved as a general rule,
I tend to keep PR closed as much as possible when solved, in order to avoid unaswered PRs to increase ( it's not the case of mine projects but I see others with tons of PRs causing reviews become difficult ).

**Comment by tannu-priya07** [comment]
thanks alot!!

**Comment by AbdullahKady** [comment]
Hey @devel0 
I just noticed you're being friendly, please close the PR, mark it as spam, and report the github profile as well.
This is a desperate attempt from the PR author to win a t-shirt through [hacktoberfest](https://hacktoberfest.digitalocean.com/).

If you don't mind, follow the [FAQ](https://hacktoberfest.digitalocean.com/faq) way of dealing with spam.

> **As a maintainer, how should I handle spam pull requests?**
> \+ We dislike seeing spam pull requests just as much as you, so please give them an invalid or spam label and close them

PS: I came across your repo without really knowing what you do, but keep being an awesome open source maintainer :clap:

**Comment by devel0** [comment]
LoL
what a strange world

**Pull request closed without merging**
